research_task:
  description: >
    Run each web search string relevant to {topic} to conduct thorough research about {topic} based on the audience level {audience_level}.
    Capture the first {search_result_ct_per_search} search results per search string. Prioritize most recent results having relevant information to {topic}.
  expected_output: >
    Capture urls associated with {topic}.
  agent: web_researcher