page_writer_task:
  description: >
    Write each entry to JSON file.
  expected_output: >
    You will be provided an input dictionary with the keys: description, directory, filename, content. 
    1. Examine the input dictionary
    2. Create a JSON file at the absolute path built from directory: {directory} and file name: {filename}.
    3. The content field will contain the JSON string version of a single RawResearchEntry object
    4. Write the JSON content to this file: 
    
    ---
    {content}
    ---
    
    5. Return a write status flag of either: WRITE_SUCCESS or WRITE_FAIL
  agent: page_writer

