page_scraper_task:
  description: >
    Scrape all content from a website corresponding to article text.
  expected_output: >
    1. Receive a URL: {scrape_url}
    2. Scrape the text from: {scrape_url}
    3. Produce a scrape result
  agent: page_scraper


save_result_task:
  description: >
    Save scraped content to file
  expected_output: >
    1. Given a ScrapeResult data structure
    2. Write a JSON file to {output_dir} of the data structure to {save_file}
  agent: page_scraper